# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13E2g0LyByR375nNTYWtMt8n1ocoqfv46
"""

import streamlit as st

def main():
    # Set app title
    st.title("Largest Number Finder")

    # Input three numbers
    number_1 = st.number_input("Enter First Number:")
    number_2 = st.number_input("Enter Second Number:")
    number_3 = st.number_input("Enter Third Number:")

    # Find the largest number
  
    largest = max(number_1, number_2, number_3)

    # Display the result
    # st.subheader("The largest number is:",st.write(largest_num))
    st.write(:red["The largest number is:"], largest)

if __name__ == '__main__':
    main()
