# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13E2g0LyByR375nNTYWtMt8n1ocoqfv46
"""

!pip install streamlit

import streamlit as st

def find_largest_number(num1, num2, num3):
    # Find the largest number
    largest_num = max(num1, num2, num3)
    return largest_num

def main():
    # Set app title
    st.title("Largest Number Finder")

    # Input three numbers
    num1 = st.number_input("Enter the first number:")
    num2 = st.number_input("Enter the second number:")
    num3 = st.number_input("Enter the third number:")

    # Find the largest number
    largest_num = find_largest_number(num1, num2, num3)

    # Display the result
    st.write("The largest number is:", largest_num)

if __name__ == '__main__':
    main()